---
title: "DoxyPep_RNA_0124"
author: "Abigail Glascock"
date: "2024-01-24"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r import}

library(tidyverse)
library(rstatix)
library(ggpubr)
library(idseqr)
library(vegan)
library(scales)
library(DESeq2)
library(ggrepel)

rename <- dplyr::rename

```

```{r theme}
theme_mine <-function(base_size=16,base_family=""){
  theme_bw(base_size,base_family=base_family) %+replace%
    theme(
      strip.background = element_blank(),
      strip.text.x = element_text(size=16),
      strip.text.y = element_text(size=16),
      axis.text.x = element_text(size=16),
      axis.text.y = element_text(size=16,hjust = 1),
      axis.ticks = element_line(colour = "black"),
      axis.title.x = element_text(size = 16),
      axis.title.y = element_text(size = 16,angle = 90, vjust=2),
      legend.position = "top", legend.text=element_text(size=16),
      panel.background = element_blank(),
      panel.border = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.spacing = unit(1.0,"lines"),
      plot.background = element_blank(),
      plot.margin = unit(c(0.5,0.5,0.5,0.5),"lines"),
      axis.line = element_line(colour = "black")
    )
}
theme_set(theme_mine())

```


# IMPORTATION

```{r set paths and read data}

idseq_sample_overviews_path = "../Inputs/Microbiome/RNA/sample_overviews_rna.csv"
ngs_samples_path = "../Inputs/Microbiome/RNA/ngs_samples_rna.csv"

### sequencing data ###
read.csv(idseq_sample_overviews_path, stringsAsFactors=F) %>%
  dplyr::mutate(
    control=dplyr::case_when(
      water_control=="Yes" ~ TRUE,
      grepl("hela", sample_name, ignore.case=T) ~ TRUE,
      TRUE ~ FALSE)) -> sample_overviews

metadata<-read.csv("../Inputs/final_sample_0116.csv", header=TRUE)
meta <-metadata %>% filter(seq=="RNA")


ptid<-read.csv("../Inputs/Microbiome/samples_w_ptid2.csv", header=TRUE)

reports_filterbg_padj <- read.csv("../Inputs/Microbiome/RNA/microbiome_reports.csv", header=TRUE)


```

# --------------------
# RESULTS: SUPPLEMENTAL FIGURES

## Supplemental Figure 5A: Microbial mass

```{r microbial load}

### wrangle data ###
reports_2<-reports_filterbg_padj %>%
  dplyr::filter(category=="bacteria")%>%
  dplyr::filter(!grepl("NTC|NEC|EMPTY|R213",sample_name)) %>%
  filter(toupper(sample_name)!="DOXYPEP_R148_C11_RECTAL_RNA_SEQ093_S51") %>% # duplicate sample with: DOXYPEP_R148_H21_RECTAL_RNA_SEQ093_S93 (keep)
  filter(toupper(sample_name)!="DOXYPEP_R137_B19_RECTAL_RNA_SEQ093_S80") %>% # duplicate sample with: DOXYPEP_R137_A11_RECTAL_RNA_SEQ093_S50 (keep)
  pivot_wider(names_from = name, values_from = nt_count, values_fill=0, id_cols = sample_name) 
reports_3<-reports_2%>%mutate(sum_bact_count=rowSums(across(where(is.numeric)))) %>% mutate(sample_name = toupper(sample_name))
reports_4<-left_join(reports_3,meta,by="sample_name")
reports_5<-reports_4 %>%
  mutate(million_reads=(total_reads/1000000)) %>%
  mutate(norm_bacterial_mass=(((sum_bact_count*2.5)/total_ercc_reads))/million_reads) %>% mutate(norm_bacterial_mass2=(((2.5*sum_bact_count)/total_ercc_reads))/million_reads)
reports_6<-reports_5 %>% mutate(arm = case_when(arm=="SOC" ~"Standard of care", arm=="DP"~"Doxy-PEP")) %>% 
  mutate(arm = factor(arm,levels=c("Standard of care","Doxy-PEP"))) %>% 
  select(sample_name,visitcode,arm,norm_bacterial_mass2)

stat.test_byvisit <-reports_6 %>% 
  mutate(visitcode=as.character(visitcode)) %>% 
  group_by(visitcode) %>% 
  wilcox_test(data=.,norm_bacterial_mass2 ~ arm) %>% 
  add_xy_position(x = "visitcode", dodge=0.8) %>% 
  mutate(y.position = 4)

stat.test_byarm <-reports_6 %>% 
  mutate(visitcode=as.character(visitcode)) %>%
  group_by(arm) %>% 
  wilcox_test(data=.,norm_bacterial_mass2 ~ visitcode) %>% 
  add_xy_position(x = "arm", dodge=0.4) %>%
  mutate(xmin = case_when(arm=="Standard of care" ~ 0.8,arm=="Doxy-PEP" ~ 1.2), 
         xmax = case_when(arm=="Standard of care" ~ 1.8, arm=="Doxy-PEP" ~ 2.2),
         y.position = case_when(arm=="Standard of care" ~ 5,arm=="Doxy-PEP" ~ 6))

stat.test <- stat.test_byvisit %>% 
  bind_rows(stat.test_byarm) %>%
  adjust_pvalue(method = "fdr") %>%
  add_significance("p.adj") %>%
  mutate(p_char = case_when(p.adj <0.1 ~ paste("p.adj =",format(p.adj, scientific = TRUE, digits = 2)),
                            TRUE ~ paste("p.adj =",
        as.character(format(round(p.adj,digits=2), nsmall =2)))))


p<-ggplot(reports_6, aes(x=as.character(visitcode), y=norm_bacterial_mass2, color=arm)) +
  scale_color_manual(values = c("#440154FF","#29AF7FFF"), na.value="gray") +
  geom_point(position = position_jitterdodge(0.3,0.2,0.6), alpha=0.6, size=4) +
  geom_boxplot(alpha=0.5, outlier.shape=NA, fill=NA, width=0.6) + 
  xlab("") + ylab("Normalized bacterial mass (pg)\n") + labs(color="") +
  stat_pvalue_manual(stat.test,  label = "{p_char}", tip.length = 0, size=4)  +
  scale_y_log10(labels = trans_format("log10", math_format(10^.x)),
                limits = c(1e-5,1e6)) +
  theme(legend.position = "top")

p

```

## Supplemental Figure 5B: Alpha diversity


``` {r alpha div}
### wrangle data ###
alpha_div<-reports_filterbg_padj %>%
  filter(nt_count>=10, nr_count>=1, nt_alignment_length >= 50) %>%
  filter(p_adj<0.1) %>%
  pivot_wider(names_from = name, values_from = nt_rpm, values_fill = 0, id_cols = sample_name) %>%
  as.data.frame()
rownames(alpha_div)<-alpha_div$sample_name
input<-alpha_div[,-1]


### calc alpha div ###
shannon<-diversity(input,index="shannon") %>% as.data.frame()
shan<-shannon %>% mutate(sample_name= rownames(shannon)) %>% rename(shannon_index='.') %>%
  mutate(sample_name=toupper(sample_name))
simp<-diversity(input,index = "simpson") %>% as.data.frame()
simp2<-simp %>% mutate(sample_name= rownames(simp)) %>% rename(simpson='.') %>%
  mutate(sample_name=toupper(sample_name))
inv<-diversity(input,index = "invsimpson") %>% as.data.frame()
inv2<-inv %>% mutate(sample_name= rownames(inv)) %>% rename(inv_simpson='.') %>%
  mutate(sample_name=toupper(sample_name))

### attach onto metadata ###
metadata<-meta %>% select(sample_name, InternalID, total_reads, total_ercc_reads, compression_ratio, batch, barcode, ptid, visitdate, visitcode_old, day0date, visitcode, arm)
data1<-left_join(metadata,shan,by="sample_name")
data2<-left_join(data1,simp2,by="sample_name")
data3<-left_join(data2,inv2,by="sample_name")
data4 <-data3 %>% 
  dplyr::filter(!grepl("NTC|NEC|EMPTY|R213",sample_name)) %>%
  filter(toupper(sample_name)!="DOXYPEP_R148_C11_RECTAL_RNA_SEQ093_S51") %>% # duplicate sample with: DOXYPEP_R148_H21_RECTAL_RNA_SEQ093_S93 (keep)
  filter(toupper(sample_name)!="DOXYPEP_R137_B19_RECTAL_RNA_SEQ093_S80") %>% # duplicate sample with: DOXYPEP_R137_A11_RECTAL_RNA_SEQ093_S50 (keep)
  mutate(arm = case_when(arm=="SOC" ~"Standard of care", arm=="DP" ~ "Doxy-PEP")) %>%
  mutate(arm = factor(arm,levels=c("Standard of care","Doxy-PEP"))) 


### PUBLICATION FIG  ###
stat.test_byvisit_shannon <-data4 %>% 
  mutate(visitcode=as.character(visitcode)) %>% 
  group_by(visitcode) %>% 
  wilcox_test(data=.,shannon_index ~ arm) %>%
  add_xy_position(x = "visitcode", dodge=0.8) %>% 
  mutate(y.position = 4)

stat.test_byarm_shannon <-data4 %>% 
  mutate(visitcode=as.character(visitcode)) %>% 
  group_by(arm) %>% 
  wilcox_test(data=.,shannon_index ~ visitcode) %>% 
  add_xy_position(x = "arm", dodge=0.4) %>%   
  mutate(xmin = case_when(arm=="Standard of care" ~ 0.8,arm=="Doxy-PEP" ~ 1.2), 
         xmax = case_when(arm=="Standard of care" ~ 1.8, arm=="Doxy-PEP" ~ 2.2),
         y.position = case_when(arm=="Standard of care" ~ 4.5,arm=="Doxy-PEP" ~ 5))

stat.test <- stat.test_byvisit_shannon %>% 
  bind_rows(stat.test_byarm_shannon) %>%
  adjust_pvalue(method = "fdr") %>%
  add_significance("p.adj") %>%
  mutate(p_char = case_when(p.adj<0.1 ~ paste("p.adj =",format(p.adj, scientific = TRUE, digits = 2)),
                            round(p.adj, digits=2)==0.05 ~ paste("p.adj =", as.character(format(round(p.adj, digits=3), nsmall = 2))),
                            TRUE ~ paste("p.adj =", as.character(format(round(p.adj, digits=2), nsmall = 2)))))

p<-ggplot(data4, aes(x=as.character(visitcode), y=shannon_index, color=arm)) +
  scale_color_manual(values = c("#440154FF","#29AF7FFF"), na.value="gray") +
  geom_point(position = position_jitterdodge(0.3,0.2,0.6), alpha=0.6, size=4) +
  geom_boxplot(alpha=0.5, outlier.shape=NA, fill=NA, width=0.6) + 
  xlab("") + ylab("Shannon Diversity Index\n") + labs(color="") +
  stat_pvalue_manual(stat.test,  label = "{p_char}", tip.length = 0, size=4)  +
  scale_y_continuous(expand=c(0,0), limits = c(0,5.5)) + 
  theme(legend.position = "top")
p

```

## Supplemental Figure 5C: Beta diversity


```{r beta div}

my_data<-reports_filterbg_padj %>%
  filter(nt_count>=10, nr_count>=1, nt_alignment_length >= 50) %>%
  filter(p_adj<0.1) %>%
  filter(category=="bacteria") %>%
  mutate(sample_name=toupper(sample_name)) %>%
  dplyr::filter(!grepl("NTC|NEC|EMPTY|R213",sample_name)) %>%
  filter(sample_name!="DOXYPEP_R148_C11_RECTAL_RNA_SEQ093_S51") %>% # duplicate sample with: DOXYPEP_R148_H21_RECTAL_RNA_SEQ093_S93 (keep)
  filter(sample_name!="DOXYPEP_R137_B19_RECTAL_RNA_SEQ093_S80") # duplicate sample with: DOXYPEP_R137_A11_RECTAL_RNA_SEQ093_S50 (keep)

combined_data<-left_join(my_data, meta, by="sample_name")
pruned_data<- combined_data %>%
  filter(visitcode=="Month 6") %>%
  select(ptid, name, nt_rpm) %>%
  pivot_wider(names_from = name, values_from = nt_rpm) %>%
  mutate_if(is.numeric, ~replace_na(., 0)) 

pruned_data2<- pruned_data[,-1]
my_data_df<-as.data.frame(pruned_data2)
rownames(my_data_df) <- pruned_data$ptid
data_transformed<-my_data_df %>% log1p() # log transform the values, with adding 1-all

pruned_metadata <- combined_data %>% select(ptid,arm) %>% distinct() %>% filter(ptid %in% rownames(my_data_df))
beta_dist <- vegdist(my_data_df)
AMR.dispersion<-betadisper(beta_dist, group=pruned_metadata$arm)
AMR.permutest<-permutest(AMR.dispersion)
plot(AMR.dispersion, hull=FALSE, ellipse=TRUE)
set.seed(100)
AMR.div<-adonis2(beta_dist ~ pruned_metadata$arm, data=pruned_metadata, permutations = 1000, method="bray")
print(AMR.div)

MDS<-metaMDS(beta_dist, distance = "bray", k=3, trymax=35, autotransform = TRUE) ##k is the number of dimensions
MDS ##metaMDS takes eaither a distance matrix or your community matrix (then requires method for ‘distance=’)

NMDS1 <- MDS$points[,1] ##also found using scores(birdMDS)
NMDS2 <- MDS$points[,2]
plot<-cbind(pruned_metadata, NMDS1, NMDS2)
cent <- aggregate(cbind(NMDS1, NMDS2) ~ arm, data = pruned_metadata, FUN = mean)
segs<-merge(plot,setNames(cent, c("arm", "oNMDS1", "oNMDS2")), by = "arm", sort = FALSE)
#plot ordination
NMDS_int<-ggplot(plot %>% mutate(arm=factor(arm, levels=c("SOC","DP"))),aes(NMDS1, NMDS2, color=arm)) +
  geom_point() +
  geom_segment(data = segs, mapping = aes(xend = oNMDS1, yend = oNMDS2, alpha=0.5)) + # spiders
  geom_point(data = cent, size = 3) +                         # centroids
  scale_color_manual(labels=c("SOC","DP"), values=c("#440154FF","#29AF7FFF")) +
  scale_fill_manual(labels=c("SOC","DP"), values=c("#440154FF","#29AF7FFF")) +
  annotate("text", x=2, y=-.75, label="Standard of care", hjust = 1, color=c("#440154FF"), size=5) +
  annotate("text", x=0, y=1.2, label="Doxy-PEP", hjust = 1, color=c("#29AF7FFF"), size=5) +
  annotate("text", x=2.5, y=-1.7, label=paste("PERMANOVA p-value 0.37"), hjust = 0, size=4) +
                theme(legend.position="none")
NMDS_int

```


